version: 2
jobs:
  build:
    docker:
      - image: cypress/browsers:chrome69
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Background the app
          command: yarn start
          background: true
      - run:
          name: Run E2E tests
          command: yarn cypress:test
          when: on_success
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots