version: '3.6'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - '3000:3000'

  cypress:
    build:
      context: .
      dockerfile: Dockerfile-cypress
    container_name: cypress
    depends_on:
      - app
    network_mode: 'host'